version: "3.9"
services:
  mysql:
    image: "mysql"
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=9gMFmlsGyd
  elasticsearch:
    image: "elasticsearch:8.3.2"
    ports:
      - "9200:9200"